baseURL = "http://samuel-killermann.netlify.com/"
languageCode = "en-us"
title = "sK"
author = "Sam Killermann"
theme= "Hugo-Paper"

[build]
publish = "public"
command = "hugo"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
pre = "<span class='emoji'>ğŸ˜</span>"
url = "/about/"
weight = -110

[[menu.main]]
name = "Now"
pre = "<span class='emoji'>âŒšï¸</span>"
url = "/now/"
weight = -100

[[menu.main]]
name = "Bio"
pre = "<span class='emoji'>ğŸ“œ</span>"
url = "/bio/"
weight = -90

[context.production.environment]
HUGO_VERSION = "0.40.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.40.1"
