baseURL = "http://example.org/"
languageCode = "en-us"
title = "sK"
author = "Sam Killermann"
theme= "Paper"
publishDir= "public"

[menu]

	[[menu.main]]
	identifier = "about"
	name = "About"
	pre = "<span class='emoji'>ğŸ˜</span>"
	url = "/about/"
	weight = -110

	[[menu.main]]
	name = "Now"
	pre = "<span class='emoji'>âŒšï¸</span>"
	url = "/now/"
	weight = -100

	[[menu.main]]
	name = "Bio"
	pre = "<span class='emoji'>ğŸ“œ</span>"
	url = "/bio/"
	weight = -90
